### ISSUE TITLE
Error con proj

### ISSUE THREAD

**Issue by frzambra** [frzambra/METE133-2024#1]
@frzambra Erro de algunos alumnos al usar project

```r
elev_proj <- terra::project(elev,'EPSG:32719') 
Error: [project] cannot get output boundaries In addition: Warning messages: 1: PROJ: proj_create_from_database: Cannot find proj.db (GDAL error 1) 2: PROJ: proj_create_from_database: Cannot find proj.db (GDAL error 1) 3: [project] Cannot set raster SRS: empty srs 
````

**Comment by Kitatakintatak** [comment]
La solución que me resultó para Windows 10, fue eliminar la variable de entorno PROJ del sistema. Al parecer la configuración incorrecta de esta variable estaba causando problemas con la localización de proj.db, lo que llevó a los errores de reproyección.

**Comment by frzambra** [comment]
Gracias. Voy a cerrar el issue
