### ISSUE TITLE
Consulta resto Taller 1 

### ISSUE THREAD

**Issue by JLBorquez** [frzambra/METE133-2024#3]
Francisco,

Ya hemos completado el taller hasta el punto revisado en clase. Continuamos intentando avanzar con lo pendiente, pero tenemos varias dudas y dificultades.

- Descargar datos de MODIS (NDVI, LST).
- Estaciones Meteorológicas.

¿Se compartirá un script guía o un recurso similar para ayudarnos?

¡Gracias!

Saludos,
JLB

**Comment by frzambra** [comment]
Subí un ejemplo con los predictores para el mes de enero, lo pueden revisar [acá](http://localhost:4423/Talleres/Taller1_ejemplo.html)
