### ISSUE TITLE
 Error in MODIStsp_download: Username and/or password are not valid. 

### ISSUE THREAD

**Issue by JLBorquez** [frzambra/METE133-2024#4]
La interfaz de MODIStsp( )no descarga archivos y muestra un error de credenciales inválidas, aunque las mismas funcionan en el sitio web de la NASA. https://urs.earthdata.nasa.gov/home

remotes::install_github("ropensci/MODIStsp", ref = "v2.1.0", force = TRUE)
hemos probado con las versiones desde 2.0.6 a la 2.1.0 y arroja el mismo error.

[Sun Sep 22 13:14:24 2024] MODIStsp --> Starting processing
[Sun Sep 22 13:14:24 2024] Accessing http server at:  https://e4ftl01.cr.usgs.gov/MOLT/MOD13A1.061/
[Sun Sep 22 13:14:26 2024] Retrieving list of available ` Terra ` Files for Year 2023
Aviso: Error in MODIStsp_download: Username and/or password are not valid. Please provide
             valid ones!

Hemos revisado antivirus y firewall y nada hasta el momento, también trabajamos  con las versiones de R 4.4.1 y R 4.3.1.

Investigando encontramos que es un problema recurrente, pero no hemos dado con la solución
https://github.com/ropensci/MODIStsp/issues/257

Agradecemos si nos pueden orientar. 
hemos llegado a un callejón sin salida. 

Saludos!!

**Comment by frzambra** [comment]
Lamentablemente el creador y mantenedor de {MODIStsp}, Lorenzo Buzzeto, falleció. Además, han habido varios cambios últimamente en como acceder a los datos, ya que se está cmabiando al uso de datos en la nube (openEO, STAC, COGs). Subí un ejemplo de como descargar datos MODIS utilizando la fuente cmr.earthdata.nasa.gov. Lo pueden revisar [acá](http://localhost:4423/Talleres/Taller1_ejemplo.html)
